"""
report_generator.py
Report generator for Spectral Uniformity Analysis
Generate PDF, Excel, and CSV reports for color uniformity measurements

Author: Olufemi Balogun
Date: November 2025
"""

import numpy as np
import pandas as pd
from datetime import datetime
from typing import Optional, Dict
from pathlib import Path

# Optional imports for PDF generation
try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    print("Warning: reportlab module not available. Install it to enable PDF report generation")



class UniformityReportGenerator:
    """
    Generate comprehensive reports for color uniformity analysis
    """
    
    def __init__(self, company_name: str = "Photonics QC Lab", author: str = "Uniformity Analysis System"):
        """
        Initialize report generator
        :param company_name: Company name for reports
        :param author: Author name for reports
        """
        self.company_name = company_name
        self.author = author
    
    def generate_pdf_report(self,
                           filename: str,
                           metrics: Dict,
                           qc_results: Dict,
                           metadata: Dict,
                           spec_limits: Dict,
                           visualization_paths: Optional[Dict[str, str]] = None) -> bool:
        """
        Generate comprehensive PDF report for uniformity analysis
        
        :param filename: Output PDF filename
        :param metrics: Uniformity metrics dictionary
        :param qc_results: QC check results dictionary
        :param metadata: Measurement metadata
        :param spec_limits: Specification limits dictionary
        :param visualization_paths: Optional dict of visualization image paths
                                     {'heatmap': path, 'distribution': path, 'chromaticity': path}
        :return: True if successful, False otherwise
        """
        if not REPORTLAB_AVAILABLE:
            print("Error: reportlab module not available")
            return False
        
        try:
            # Create PDF document
            doc = SimpleDocTemplate(filename, pagesize=letter)
            story = []
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=colors.HexColor('#1f4788'),
                spaceAfter=30,
                alignment=TA_CENTER
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=14,
                textColor=colors.HexColor('#1f4788'),
                spaceAfter=12,
                spaceBefore=12,
            )
            
            subheading_style = ParagraphStyle(
                'CustomSubheading',
                parent=styles['Heading3'],
                fontSize=12,
                textColor=colors.HexColor('#2c5aa0'),
                spaceAfter=8,
                spaceBefore=8,
            )
            
            # Title
            story.append(Paragraph("Color Uniformity Analysis Report", title_style))
            story.append(Spacer(1, 0.2*inch))
            
            # Timestamp and Report Info
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            story.append(Paragraph(f"<b>Report Generated:</b> {timestamp}", styles['Normal']))
            story.append(Paragraph(f"<b>Generated By:</b> {self.author}", styles['Normal']))
            story.append(Paragraph(f"<b>Company:</b> {self.company_name}", styles['Normal']))
            story.append(Spacer(1, 0.3*inch))
            
            # Device and Measurement Information
            story.append(Paragraph("Measurement Information", heading_style))
            
            meta_data = [
                ['Parameter', 'Value'],
                ['Device Serial', metadata.get('device_serial', 'N/A')],
                ['Operator', metadata.get('operator', 'N/A')],
                ['Instrument', metadata.get('instrument_model', 'N/A')],
                ['Instrument Serial', metadata.get('instrument_serial', 'N/A')],
                ['Calibration Date', metadata.get('calibration_date', 'N/A')],
                ['Temperature', f"{metadata.get('temperature_c', 'N/A')} °C"],
                ['Humidity', f"{metadata.get('humidity_percent', 'N/A')} %"],
                ['Ambient Light', f"{metadata.get('ambient_light_lux', 'N/A')} lux"],
            ]
            
            meta_table = Table(meta_data, colWidths=[2.5*inch, 4*inch])
            meta_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f4788')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('BACKGROUND', (0, 1), (0, -1), colors.HexColor('#e8f4f8')),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            story.append(meta_table)
            story.append(Spacer(1, 0.3*inch))
            
            # QC Results Summary
            story.append(Paragraph("QC Test Results", heading_style))
            
            # Pass/Fail status
            status = "PASS" if qc_results.get('pass', False) else "FAIL"
            status_color = colors.green if qc_results.get('pass', False) else colors.red
            
            status_style = ParagraphStyle(
                'Status',
                parent=styles['Normal'],
                fontSize=18,
                textColor=status_color,
                alignment=TA_CENTER,
                fontName='Helvetica-Bold'
            )
            
            story.append(Paragraph(f"Overall Result: {status}", status_style))
            story.append(Spacer(1, 0.2*inch))
            
            # Uniformity Metrics
            story.append(Paragraph("Uniformity Metrics", subheading_style))
            
            metrics_data = [
                ['Metric', 'Value', 'Specification', 'Status'],
                ['Mean ΔE*00', f"{metrics['deltaE_mean']:.2f}", 
                 f"< {spec_limits.get('max_deltaE_mean', 'N/A')}", 
                 '✓' if metrics['deltaE_mean'] < spec_limits.get('max_deltaE_mean', float('inf')) else '✗'],
                ['Max ΔE*00', f"{metrics['deltaE_max']:.2f}", 
                 f"< {spec_limits.get('max_deltaE_any', 'N/A')}", 
                 '✓' if metrics['deltaE_max'] < spec_limits.get('max_deltaE_any', float('inf')) else '✗'],
                ['Std Dev ΔE*00', f"{metrics['deltaE_std']:.2f}", 
                 f"< {spec_limits.get('max_deltaE_std', 'N/A')}", 
                 '✓' if metrics['deltaE_std'] < spec_limits.get('max_deltaE_std', float('inf')) else '✗'],
                ['Median ΔE*00', f"{metrics['deltaE_median']:.2f}", '-', '-'],
            ]
            
            metrics_table = Table(metrics_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1*inch])
            metrics_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f4788')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f0f0')])
            ]))
            story.append(metrics_table)
            story.append(Spacer(1, 0.2*inch))
            
            # Color Statistics
            story.append(Paragraph("Color Statistics (CIELAB)", subheading_style))
            
            color_data = [
                ['Component', 'Mean', 'Std Dev', 'Min', 'Max'],
                ['L* (Lightness)', f"{metrics['Lab_mean']:.1f}", f"{metrics['Lab_std']:.1f}", 
                 f"{metrics.get('Lab_min', 0):.1f}", f"{metrics.get('Lab_max', 100):.1f}"],
                ['a* (Red-Green)', f"{metrics['a_mean']:.2f}", f"{metrics['a_std']:.2f}", 
                 f"{metrics.get('a_min', 0):.2f}", f"{metrics.get('a_max', 0):.2f}"],
                ['b* (Yellow-Blue)', f"{metrics['b_mean']:.2f}", f"{metrics['b_std']:.2f}", 
                 f"{metrics.get('b_min', 0):.2f}", f"{metrics.get('b_max', 0):.2f}"],
            ]
            
            color_table = Table(color_data, colWidths=[1.5*inch, 1.25*inch, 1.25*inch, 1.25*inch, 1.25*inch])
            color_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f4788')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f0f0')])
            ]))
            story.append(color_table)
            story.append(Spacer(1, 0.2*inch))
            
            # Chromaticity Statistics
            story.append(Paragraph("Chromaticity Uniformity (CIE 1931 xy)", subheading_style))
            
            chrom_data = [
                ['Metric', 'Value', 'Specification', 'Status'],
                ['Mean xy Deviation', f"{metrics['xy_deviation_mean']:.4f}", 
                 f"< {spec_limits.get('chromaticity_tolerance', 'N/A')}", 
                 '✓' if metrics['xy_deviation_mean'] < spec_limits.get('chromaticity_tolerance', float('inf')) else '✗'],
                ['Max xy Deviation', f"{metrics['xy_deviation_max']:.4f}", 
                 f"< {spec_limits.get('chromaticity_tolerance', 'N/A')}", 
                 '✓' if metrics['xy_deviation_max'] < spec_limits.get('chromaticity_tolerance', float('inf')) else '✗'],
            ]
            
            chrom_table = Table(chrom_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1*inch])
            chrom_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f4788')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f0f0')])
            ]))
            story.append(chrom_table)
            story.append(Spacer(1, 0.3*inch))
            
            # Worst Position
            worst_pos = metrics.get('max_deltaE_position', (0, 0))
            story.append(Paragraph(f"<b>Worst Position:</b> ({worst_pos[0]:.1f}, {worst_pos[1]:.1f}) mm with ΔE = {metrics['deltaE_max']:.2f}", styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
            
            # Failures and Warnings
            if qc_results.get('failures'):
                story.append(Paragraph("Failures", subheading_style))
                for failure in qc_results['failures']:
                    story.append(Paragraph(f"• {failure}", styles['Normal']))
                story.append(Spacer(1, 0.2*inch))
            
            if qc_results.get('warnings'):
                story.append(Paragraph("Warnings", subheading_style))
                for warning in qc_results['warnings']:
                    story.append(Paragraph(f"• {warning}", styles['Normal']))
                story.append(Spacer(1, 0.2*inch))
            
            # Add visualizations if provided
            if visualization_paths:
                story.append(PageBreak())
                story.append(Paragraph("Uniformity Visualizations", heading_style))
                
                if 'heatmap' in visualization_paths and Path(visualization_paths['heatmap']).exists():
                    story.append(Paragraph("Uniformity Heatmap", subheading_style))
                    img = Image(visualization_paths['heatmap'], width=6*inch, height=4.5*inch)
                    story.append(img)
                    story.append(Spacer(1, 0.2*inch))
                
                if 'distribution' in visualization_paths and Path(visualization_paths['distribution']).exists():
                    story.append(Paragraph("ΔE Distribution", subheading_style))
                    img = Image(visualization_paths['distribution'], width=6*inch, height=4.5*inch)
                    story.append(img)
                    story.append(Spacer(1, 0.2*inch))
                
                if 'chromaticity' in visualization_paths and Path(visualization_paths['chromaticity']).exists():
                    story.append(PageBreak())
                    story.append(Paragraph("Chromaticity Diagram", subheading_style))
                    img = Image(visualization_paths['chromaticity'], width=6*inch, height=4.5*inch)
                    story.append(img)
            
            # Notes
            if metadata.get('notes'):
                story.append(PageBreak())
                story.append(Paragraph("Notes", heading_style))
                story.append(Paragraph(metadata['notes'], styles['Normal']))
            
            # Footer
            story.append(Spacer(1, 0.5*inch))
            footer_text = f"Generated by {self.author} | {self.company_name}"
            story.append(Paragraph(footer_text, styles['Normal']))
            
            # Build PDF
            doc.build(story)
            
            print(f"✓ PDF report generated: {filename}")
            return True
        
        except Exception as e:
            print(f"✗ Error generating PDF report: {e}")
            import traceback
            traceback.print_exc()
            return False
    
    def generate_csv_report(self,
                           filename: str,
                           metrics: Dict,
                           qc_results: Dict,
                           metadata: Dict,
                           spec_limits: Dict) -> bool:
        """
        Generate CSV report with analysis results
        
        :param filename: Output CSV filename
        :param metrics: Uniformity metrics dictionary
        :param qc_results: QC check results dictionary
        :param metadata: Measurement metadata
        :param spec_limits: Specification limits dictionary
        :return: True if successful, False otherwise
        """
        try:
            with open(filename, 'w') as f:
                # Write header
                f.write("# Color Uniformity Analysis Report\n")
                f.write(f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"# Author: {self.author}\n")
                f.write("#\n")
                
                # Metadata
                f.write("# Measurement Information:\n")
                f.write(f"# Device Serial: {metadata.get('device_serial', 'N/A')}\n")
                f.write(f"# Operator: {metadata.get('operator', 'N/A')}\n")
                f.write(f"# Instrument: {metadata.get('instrument_model', 'N/A')}\n")
                f.write(f"# Instrument Serial: {metadata.get('instrument_serial', 'N/A')}\n")
                f.write(f"# Calibration Date: {metadata.get('calibration_date', 'N/A')}\n")
                f.write(f"# Temperature: {metadata.get('temperature_c', 'N/A')} °C\n")
                f.write(f"# Humidity: {metadata.get('humidity_percent', 'N/A')} %\n")
                f.write("#\n")
                
                # QC Results
                status = "PASS" if qc_results.get('pass', False) else "FAIL"
                f.write(f"# QC Result: {status}\n")
                f.write("#\n")
                
                # Uniformity Metrics
                f.write("# Uniformity Metrics:\n")
                f.write(f"# Mean ΔE*00: {metrics['deltaE_mean']:.2f} (Spec: < {spec_limits.get('max_deltaE_mean', 'N/A')})\n")
                f.write(f"# Max ΔE*00: {metrics['deltaE_max']:.2f} (Spec: < {spec_limits.get('max_deltaE_any', 'N/A')})\n")
                f.write(f"# Std Dev ΔE*00: {metrics['deltaE_std']:.2f} (Spec: < {spec_limits.get('max_deltaE_std', 'N/A')})\n")
                f.write(f"# Median ΔE*00: {metrics['deltaE_median']:.2f}\n")
                f.write("#\n")
                
                # Color Statistics
                f.write("# Color Statistics (CIELAB):\n")
                f.write(f"# L* (Lightness): {metrics['Lab_mean']:.1f} ± {metrics['Lab_std']:.1f}\n")
                f.write(f"# a* (Red-Green): {metrics['a_mean']:.2f} ± {metrics['a_std']:.2f}\n")
                f.write(f"# b* (Yellow-Blue): {metrics['b_mean']:.2f} ± {metrics['b_std']:.2f}\n")
                f.write("#\n")
                
                # Chromaticity
                f.write("# Chromaticity Uniformity:\n")
                f.write(f"# Mean xy Deviation: {metrics['xy_deviation_mean']:.4f}\n")
                f.write(f"# Max xy Deviation: {metrics['xy_deviation_max']:.4f}\n")
                f.write("#\n")
                
                # Failures
                if qc_results.get('failures'):
                    f.write("# Failures:\n")
                    for failure in qc_results['failures']:
                        f.write(f"# - {failure}\n")
                    f.write("#\n")
                
                # Warnings
                if qc_results.get('warnings'):
                    f.write("# Warnings:\n")
                    for warning in qc_results['warnings']:
                        f.write(f"# - {warning}\n")
                    f.write("#\n")
                
                # Worst Position
                worst_pos = metrics.get('max_deltaE_position', (0, 0))
                f.write(f"# Worst Position: ({worst_pos[0]:.1f}, {worst_pos[1]:.1f}) mm with ΔE = {metrics['deltaE_max']:.2f}\n")
                f.write("#\n")
                
                # Data section header
                f.write("# Detailed measurement data available in separate data CSV file\n")
            
            print(f"✓ CSV report generated: {filename}")
            return True
        
        except Exception as e:
            print(f"✗ Error generating CSV report: {e}")
            return False


# Test code
if __name__ == "__main__":
    print("=== Uniformity Report Generator Test ===\n")
    
    # Mock data for testing
    test_metrics = {
        'deltaE_mean': 1.85,
        'deltaE_median': 1.72,
        'deltaE_std': 0.89,
        'deltaE_min': 0.15,
        'deltaE_max': 4.32,
        'deltaE_values': np.random.uniform(0, 5, 25),
        'Lab_mean': 85.3,
        'Lab_std': 2.1,
        'a_mean': -2.35,
        'a_std': 1.22,
        'b_mean': 5.67,
        'b_std': 1.89,
        'xy_deviation_mean': 0.0045,
        'xy_deviation_max': 0.0092,
        'max_deltaE_position': (7.5, 2.5),
    }
    
    test_qc_results = {
        'pass': True,
        'failures': [],
        'warnings': ['Mean ΔE approaching specification limit'],
    }
    
    test_metadata = {
        'device_serial': 'TEST-DEVICE-001',
        'operator': 'Test User',
        'instrument_model': 'Test Spectrometer',
        'instrument_serial': 'TEST-12345',
        'calibration_date': '2025-11-01',
        'temperature_c': 23.5,
        'humidity_percent': 45.0,
        'ambient_light_lux': 0.3,
        'notes': 'Test measurement for report generator validation',
    }
    
    test_spec_limits = {
        'max_deltaE_mean': 3.0,
        'max_deltaE_any': 5.0,
        'max_deltaE_std': 2.0,
        'chromaticity_tolerance': 0.01,
    }
    
    generator = UniformityReportGenerator()
    
    # Test CSV report
    print("1. Generating CSV report...")
    generator.generate_csv_report(
        "test_uniformity_report.csv",
        test_metrics,
        test_qc_results,
        test_metadata,
        test_spec_limits
    )
    
    # Test PDF report
    if REPORTLAB_AVAILABLE:
        print("\n2. Generating PDF report...")
        generator.generate_pdf_report(
            "test_uniformity_report.pdf",
            test_metrics,
            test_qc_results,
            test_metadata,
            test_spec_limits
        )
    else:
        print("\n2. PDF report generation not available (reportlab not installed)")
    
    print("\n=== Report Generator Test Complete ===")

